(function(d){var p={},e,a,h=document,i=window,f=h.documentElement,j=d.expando;d.event.special.inview={add:function(a){p[a.guid+"-"+this[j]]={data:a,$element:d(this)}},remove:function(a){try{delete p[a.guid+"-"+this[j]]}catch(d){}}};d(i).bind("scroll resize",function(){e=a=null});!f.addEventListener&&f.attachEvent&&f.attachEvent("onfocusin",function(){a=null});setInterval(function(){var k=d(),j,n=0;d.each(p,function(a,b){var c=b.data.selector,d=b.$element;k=k.add(c?d.find(c):d)});if(j=k.length){var b;if(!(b=e)){var g={height:i.innerHeight,width:i.innerWidth};if(!g.height&&((b=h.compatMode)||!d.support.boxModel))b="CSS1Compat"===b?f:h.body,g={height:b.clientHeight,width:b.clientWidth};b=g}e=b;for(a=a||{top:i.pageYOffset||f.scrollTop||h.body.scrollTop,left:i.pageXOffset||f.scrollLeft||h.body.scrollLeft};n<j;n++)if(d.contains(f,k[n])){b=d(k[n]);var l=b.height(),m=b.width(),c=b.offset(),g=b.data("inview");if(!a||!e)break;c.top+l>a.top&&c.top<a.top+e.height&&c.left+m>a.left&&c.left<a.left+e.width?(m=a.left>c.left?"right":a.left+e.width<c.left+m?"left":"both",l=a.top>c.top?"bottom":a.top+e.height<c.top+l?"top":"both",c=m+"-"+l,(!g||g!==c)&&b.data("inview",c).trigger("inview",[!0,m,l])):g&&b.data("inview",!1).trigger("inview",[!1])}}},250)})(jQuery);jQuery(function($){$(document).ajaxComplete(function(){try{FB.XFBML.parse();twttr.widgets.load();gapi.plusone.go();}catch(e){console.log(e);}});$(document).ready(function(){if($('body.nicescroll').length){$("html, .main_menu").niceScroll({styler:"fb",cursorborder:0,background:"#fff",cursorcolor:"#ff6825",cursoropacitymin:0.4,cursoropacitymax:1,cursorborderradius:0,cursorwidth:10,horizrailenabled:false,zindex:8000});}
if($('.video_posts_section').length){$('.video_posts_section .playlist').mCustomScrollbar({horizontalScroll:true,advanced:{autoExpandHorizontalScroll:true}});$('.video_posts_section .playlist a').on('click',function(event){event.preventDefault();var videoSection=$(this).parents('.video_posts_section');if(videoSection.find('.overlay').length){videoSection.find('.overlay').fadeIn();}else{videoSection.append('<div class="overlay"><img src="'+$xurl+'fancybox_loading.gif" alt=""></div>').fadeIn();}
$.ajax({url:$xurl+'videoSectionFunctionality.php',type:'POST',dataType:'json',data:{post_id:parseInt($(this).attr('data-id')),video_url:$(this).attr('data-video')},success:function(data){$('.video_posts_section .player iframe, .video_posts_section .article').remove();$('.video_posts_section .player').append(data.video);$('.video_posts_section .player').after(data.content);videoSection.find('.overlay').fadeOut();}});});}
$('.menu-toggle').on('touchstart click',function(event){if(window.innerWidth>768){if($('header .main_menu').hasClass('active')){$('header .main_menu').removeClass('active').fadeOut();$('header .main_menu').find('h3, ul').each(function(){$(this).removeClass('animated fadeInUp');});}else{$('header .main_menu').addClass('active').fadeIn();$('header .main_menu').find('h3, ul').each(function(){$(this).addClass('animated fadeInUp');});}}else{if($('header .main_menu').hasClass('active')){$('.site, .menu-toggle').animate({'right':'0'},function(){$(this).removeAttr('style');$('.menu-toggle').removeClass('active');});$('header .main_menu').animate({'left':'100%'},function(){$(this).removeClass('active').removeAttr('style');});}else{$('.site, .menu-toggle').animate({'right':'60%'});$('header .main_menu').addClass('active').animate({'left':'40%'});}}
if(!$('.menu-toggle').hasClass('active')){$('.menu-toggle').addClass('active');}else{$('.menu-toggle').removeClass('active');}
event.preventDefault();});$(window).resize(function(){$('.site, .menu-toggle,.main_menu').removeClass('active').removeAttr('style');$('header .main_menu').find('h3, ul').each(function(){$(this).removeClass('animated fadeInUp');});});if($('.single-image .hero .slider').length){$('.header_bg .item0').show().siblings('.bg_stretch').hide();$(".hero .slider").carouFredSel({items:{visible:1},scroll:{duration:500,fx:'crossfade',items:1,pauseOnHover:'resume',onBefore:function(data){data.items.old.each(function(i){$('.hero .item').removeClass('fadeInLeft').addClass('fadeOutRight');});},onAfter:function(data){$(this).delay(1000);var pos=$('.hero .slider').triggerHandler('currentPosition');data.items.visible.each(function(i){$('.header_bg .item'+pos).fadeIn().siblings('.bg_stretch').fadeOut();$('.hero .item').removeClass('fadeOutRight')
$('.hero .item.item'+pos).addClass('current animated fadeInLeft').siblings().removeClass('current');});}},auto:{play:true,timeoutDuration:7000,delay:2000},swipe:{onTouch:true,onMouse:true},prev:{button:'.slider_nav .btn-prev',onBefore:function(data){data.items.old.each(function(i){$('.hero .item').removeClass('fadeInLeft fadeOutRight fadeOutLeft fadeInRight').addClass('fadeOutRight');});},onAfter:function(data){$(this).delay(1000);var pos=$('.hero .slider').triggerHandler('currentPosition');data.items.visible.each(function(i){$('.header_bg .item'+pos).fadeIn().siblings('.bg_stretch').fadeOut();$('.hero .item').removeClass('fadeInLeft fadeOutRight fadeOutLeft fadeInRight')
$('.hero .item.item'+pos).addClass('current animated fadeInLeft').siblings().removeClass('current');});}},next:{button:'.slider_nav .btn-next',onBefore:function(data){data.items.old.each(function(i){$('.hero .item').removeClass('fadeInLeft fadeOutRight fadeOutLeft fadeInRight').addClass('fadeOutLeft');});},onAfter:function(data){$(this).delay(1000);var pos=$('.hero .slider').triggerHandler('currentPosition');data.items.visible.each(function(i){$('.header_bg .item'+pos).fadeIn().siblings('.bg_stretch').fadeOut();$('.hero .item').removeClass('fadeInLeft fadeOutRight fadeOutLeft fadeInRight')
$('.hero .item.item'+pos).addClass('current animated fadeInRight').siblings().removeClass('current');});}},pagination:{container:'.slider_pagination'},});}
if($('.home .hero .slider').length){$(".hero .slider").carouFredSel({responsive:true,items:{visible:1},scroll:{duration:600,fx:'directscroll',pauseOnHover:'resume'},auto:{play:true,timeoutDuration:7000,delay:2000},swipe:{onTouch:true,onMouse:true},prev:{button:'.slider_nav .btn-prev',onBefore:function(data){data.items.old.each(function(i){$('.hero .item').removeClass('fadeInLeft fadeOutRight fadeOutLeft fadeInRight').addClass('fadeOutRight');});},onAfter:function(data){var pos=$('.hero .slider').triggerHandler('currentPosition');data.items.visible.each(function(i){$('.hero .item').removeClass('current fadeInLeft fadeOutRight fadeOutLeft fadeInRight');$('.hero .item.item'+pos).addClass('current animated fadeInLeft');});}},next:{button:'.slider_nav .btn-next',onBefore:function(data){data.items.old.each(function(i){$('.hero .item').removeClass('fadeInLeft fadeOutRight fadeOutLeft fadeInRight').addClass('fadeOutLeft');});},onAfter:function(data){var pos=$('.hero .slider').triggerHandler('currentPosition');data.items.visible.each(function(i){$('.hero .item').removeClass('current fadeInLeft fadeOutRight fadeOutLeft fadeInRight');$('.hero .item.item'+pos).addClass('current animated fadeInRight');});}}});}
if($('.recent_comments_widget').length){$('.recent_comments_widget .recentComments').carouFredSel({direction:'down',items:{visible:3},scroll:{items:1},auto:{play:false},prev:{button:'.recent_comments_widget .nav_top'},next:{button:'.recent_comments_widget .nav_bottom'},swipe:{onTouch:true,onMouse:true},});}
if($('.tab_content').length){$('.tab_content .tabs a').on('click',function(event){var tab=$(this).parent().index();$(this).parent().addClass('current').siblings().removeClass('current');$('.tab_content .tab_boxes .content').eq(tab).show().siblings().hide();event.preventDefault();});}
if($('#playlist-scroll').length){$("#playlist-scroll").niceScroll({cursorborder:0,background:"#1a1313",cursorcolor:"#fff",cursoropacitymin:0.4,cursoropacitymax:1,cursorborderradius:0,cursorwidth:10,boxzoom:false,touchbehavior:true});}
if($('.gallery_wp_wrapper').length){$('.gallery_wp_wrapper .gallery_list').each(function(){var gallery=$(this);gallery.next('.gallery_pagination').find('.bullet_img').each(function(i){$(this).addClass('itm'+i);$(this).click(function(){gallery.find('.gallery').trigger('slideTo',[i,0,true]);return false;});});gallery.next('.gallery_pagination').find('.bullet_img:first-child').addClass('current');$(this).find('.gallery').carouFredSel({responsive:true,items:{visible:1,height:'100%'},scroll:{duration:500,fx:'cover',items:1,pauseOnHover:'resume',onBefore:function(data){data.items.old.each(function(i){var pos=gallery.find('.gallery').triggerHandler('currentPosition');gallery.next('.gallery_pagination').find('.bullet_img').removeClass('current');gallery.next('.gallery_pagination').find('.bullet_img.itm'+pos).addClass('current');});}},prev:{fx:'uncover'},next:{fx:'cover'},auto:{play:true,timeoutDuration:7000,delay:2000},swipe:{onTouch:true,onMouse:true},});});}
if($('.fancybox').length){$(document).ready(function(){$(".fancybox").fancybox({openEffect:'none',closeEffect:'none'});});}
if($('.review').length){function checkScrollingForLines(){var delay=1600;var bar_delay=600;$('.review .line span').each(function(){var width=$(this).attr('data-val')+'%';$(this).stop(true,true).delay(delay).animate({'width':width},1400);delay+=bar_delay;});}
$('.review').one('inview',function(event,isInView){if(isInView){checkScrollingForLines();$('.review .overal').countTo({from:0,to:$('.review .overal').attr('data-val'),speed:3000,refreshInterval:50,onUpdate:function(value){$('.review .overal').removeClass('count'+(value.toFixed()-1)).addClass('count'+value.toFixed());}});}});}
function setHeroHeight(){if(screen.width>998||window.innerWidth>998){if($('.single-image').length){$('.single-image .hero').height($(window).height()- $('.header > .top').height()+ 36);}
if($('.home').length&&!$('.home-page').length){if(window.innerHeight>800){$('.home .hero').height($(window).height()-($('.header > .top').height()*1.5));}else{$('.home .hero').height($(window).height()- 50);}}
if($('.header > .avatar').length){setAvatar();}}}
setHeroHeight();function setAvatar(){var position=$('.main').offset();var elemWidth=$('.main').innerWidth()/ 2;
$('.header > .avatar').css('left',position.left+ elemWidth);}
if(screen.width<1400&&screen.width>998||window.innerWidth<1400&&window.innerWidth>998){$('.main.content').css({'min-height':$('.container aside.left').height()+ $('.container aside.right').height()+ 300});}
$(window).resize(function(){if(screen.width<1400&&screen.width>998||window.innerWidth<1400&&window.innerWidth>998){$('.main.content').css({'min-height':$('.container aside.left').height()+ $('.container aside.right').height()+ 100});}else{$('.main.content').removeAttr('style');}
if(window.innerWidth>768){$('.header, .container, .video_posts_section, #most_popular, footer.transitionAll').removeAttr('style');$('header .main_menu').removeClass('transitionAll').removeAttr('style');$('.menu-toggle').removeClass('active');}
setHeroHeight();});$('.like').live('click',function(e){e.preventDefault();var button=$(this);$.ajax({url:$xurl+'likeFunctionality.php',type:'POST',dataType:'json',data:{post_id:parseInt($(this).attr('data-likeid')),ip_address:"get",like:1},success:function(data){button.html(data.likeCount);}});});$('.dislike').live('click',function(e){e.preventDefault();var button=$(this);$.ajax({url:$xurl+'likeFunctionality.php',type:'POST',dataType:'json',data:{post_id:parseInt($(this).attr('data-dislikeid')),ip_address:"get",dislike:1},success:function(data){button.html(data.likeCount);}});});$('.newsletter_widget .btn').on('click',function(e){e.preventDefault();var $ok=true;var $input=$(this).prev('input[name=email]');var $email=$input.val();$(this).parent().removeClass('error').each(function(){if($(this).find('input[name=email]').val()===''){$(this).addClass('error');$ok=false;}
if(!validateEmail($email)){$(this).find('input[name=email]').parent().addClass('error');$ok=false;}});if($ok){$.ajax({url:$xurl+'contact-script.php',type:'POST',dataType:'json',data:$(this).parents('form').serialize(),success:function(data){$input.after('<p class="alert">'+data.error+'</p>').next('.alert').hide().fadeIn(300);$input.val('');$input.next('.alert').delay(8000).fadeOut();setTimeout(function(){$input.next('.alert').remove();},9000);}});}
return false;});function validateEmail(sEmail){var filter=/^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/;if(filter.test(sEmail)){return true;}else{return false;}}
if($('#most_popular .wrap.inner.box').length){var cloneItem=$('#most_popular .wrap.inner.box:first').clone();for(i=0;i<2;i++){cloneItem.insertAfter('#most_popular .wrap.inner.box');}}
if($('#wp-calendar tfoot td').not('#today').find('a').length){$('#wp-calendar tfoot td').not('#today').find('a').each(function(){var text=$('#wp-calendar tfoot td').not('#today').find('a').text();text=text.replace(/[«»]/g,"");$(this).text(text);});}
if($('.recentComments').length){var oneItem=$('.recentComments .comment').outerHeight();var itemsHeight=oneItem*$('.recentComments .comment').length;var contentHeight=$('.commentsSlide').outerHeight();if(itemsHeight<$('.commentsSlide').innerHeight()){$('.commentsSlide').height(itemsHeight- oneItem);}else{var itemslength=Math.round(contentHeight/oneItem);$('.commentsSlide').height(oneItem*itemslength);}}});});